[package]
name = "get-longhorn-backup"
version = "0.1.0"
edition = "2021"

[dependencies]
async-stream = "0.3"
futures-core = "0.3"
futures-util = "0.3"
lz4 = "1.27"
rust-s3 = "0.35"
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
